#!/bin/sh
# $Id$
# Icinga	Startup script for the Nagios monitoring daemon
#
# chkconfig:	- 85 15
# description:	Icinga is a service monitoring system
# processname: icinga
# config: /usr/local/icinga/etc/icinga.cfg
# pidfile: /var/run/icinga.pid
#
### BEGIN INIT INFO
# Provides:		icinga
# Required-Start:	$local_fs $syslog $network
# Required-Stop:	$local_fs $syslog $network
# Short-Description:    start and stop Icinga monitoring server
# Description:		Icinga is is a service monitoring system 
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

user="icinga"
prog="icinga"
prefix="/usr/local/$prog"
exec_prefix="${prefix}"
exec="${prefix}/bin/$prog"
config="${prefix}/etc/$prog.cfg"
piddir="/var/run"
lockdir="/var/lock/subsys"
pidfile="$piddir/$prog.pid"
lockfile="${lockdir}/$prog"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon --user=$user $exec -d $config
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -d 10 $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile $pidfile
    return $retval
}


restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc $exec -HUP
    retval=$?
    echo
}

force_reload() {
    restart
}

check_config() {
        $nice runuser -s /bin/bash - $user -c "$corelimit >/dev/null 2>&1 ; $exec -v $config > /dev/null 2>&1"
        retval=$?
        if [ $retval -ne 0 ] ; then
                echo -n $"Configuration validation failed"
                failure
                echo
                exit 1

        fi
}


case "$1" in
    start)
        status $prog && exit 0
	check_config
        $1
        ;;
    stop)
        status $prog|| exit 0
        $1
        ;;
    restart)
	check_config
        $1
        ;;
    reload)
        status $prog || exit 7
	check_config
        $1
        ;;
    force-reload)
	check_config
        force_reload
        ;;
    status)
        status $prog
        ;;
    condrestart|try-restart)
        status $prog|| exit 0
	check_config
        restart
        ;;
    configtest)
        echo -n  $"Checking config for $prog: "
        check_config && success
        echo
	;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload|configtest}"
        exit 2
esac
exit $?

